### ISSUE TITLE
fix review findings - remove restart adaüters

### ISSUE THREAD

**Issue by boellner** [boellner/ioBroker.openknx#7]
You do not need to list yourself as restartAdapters https://github.com/iobroker-community-adapters/ioBroker.openknx/blob/master/io-package.json#L73

**Comment by TA2k** [comment]
Fixed with 
https://github.com/iobroker-community-adapters/ioBroker.openknx/commit/c383547de3a3bc84cd3e87ef3153e880090c6ce2
